"""create debt payments and update debts

Revision ID: e50e775fbdc4
Revises: dc93e1b691c3
Create Date: 2026-08-12 21:08:31.989860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e50e775fbdc4'
down_revision: Union[str, None] = 'dc93e1b691c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debt_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debt_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['debt_id'], ['debts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debt_payments_account_id'), 'debt_payments', ['account_id'], unique=False)
    op.create_index(op.f('ix_debt_payments_debt_id'), 'debt_payments', ['debt_id'], unique=False)
    op.create_index(op.f('ix_debt_payments_id'), 'debt_payments', ['id'], unique=False)
    op.add_column('debts', sa.Column('status', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('debts', 'status')
    op.drop_index(op.f('ix_debt_payments_id'), table_name='debt_payments')
    op.drop_index(op.f('ix_debt_payments_debt_id'), table_name='debt_payments')
    op.drop_index(op.f('ix_debt_payments_account_id'), table_name='debt_payments')
    op.drop_table('debt_payments')
    # ### end Alembic commands ###
